-- 대출 받지 않은 고객 ID
SELECT CUSTOMER_ID FROM CUSTOMERS
MINUS
SELECT CUSTOMER_ID FROM LOANS;


-- 거래 테이블과 계좌 테이블에 공통적으로 존재하는 계좌 ID 출력
SELECT ACCOUNT_ID FROM TRANSACTIONS
INTERSECT
SELECT ACCOUNT_ID FROM ACCOUNTS;


-- 대출 내역이 없는 지점 ID 조회
SELECT BRANCH_ID FROM BRANCHES
MINUS
SELECT BRANCH_ID FROM LOANS;
 
