-- 지점이 'Location 1'에 해당하는 지점에서 대출을 받은 고객의 이름 출력
SELECT C.NAME
FROM LOANS L, CUSTOMERS C
WHERE L.CUSTOMER_ID = C.CUSTOMER_ID 
    AND L.BRANCH_ID IN (SELECT BRANCH_ID FROM BRANCHES WHERE LOCATION = 'Location 1');

SELECT (SELECT NAME FROM CUSTOMERS WHERE CUSTOMER_ID = L.CUSTOMER_ID) CUSTOMER_NAME
FROM LOANS L
WHERE L.BRANCH_ID IN (SELECT BRANCH_ID FROM BRANCHES WHERE LOCATION = 'Location 1');

-- 특정 고객 (CUSTOMER_ID = 100)이 소유한 모든 계좌에서 발생한 거래 출력
SELECT *
FROM TRANSACTIONS T
WHERE T.ACCOUNT_ID IN (SELECT ACCOUNT_ID FROM ACCOUNTS A 
                        WHERE A.CUSTOMER_ID = 100);


-- 각 고객이 보유한 계좌 중 가장 높은 잔액 계좌
SELECT A.CUSTOMER_ID, A.ACCOUNT_ID, BALANCE
FROM ACCOUNTS A
WHERE BALANCE = (SELECT MAX(BALANCE) FROM ACCOUNTS WHERE A.CUSTOMER_ID = CUSTOMER_ID);

