SELECT * FROM CUSTOMERS;
SELECT * FROM ACCOUNT;
SELECT * FROM ACCOUNTS;
SELECT * FROM TRANSACTIONS;
SELECT * FROM LOANS;


-- 실습과제 1
SELECT NAME, EMAIL FROM CUSTOMERS;

SELECT ACCOUNT_ID, BALANCE FROM ACCOUNTS;

SELECT AMOUNT, TRANSACTION_TYPE FROM TRANSACTIONS;

-- 실습과제 2
SELECT NAME, PHONE
FROM CUSTOMERS
WHERE ADDRESS = 'Address 100';

SELECT ACCOUNT_ID, BALANCE 
FROM ACCOUNTS
WHERE BALANCE >= 50000;

SELECT TRANSACTION_ID, AMOUNT 
FROM TRANSACTIONS
WHERE AMOUNT < 0;

SELECT AMOUNT, CUSTOMER_ID
FROM LOANS
WHERE STATUS = 'APPROVED';

-- 실습과제 3
SELECT NAME, EMAIL
FROM CUSTOMERS
WHERE PHONE LIKE '555-1000%';

SELECT ACCOUNT_ID, BALANCE
FROM ACCOUNTS
WHERE ACCOUNT_TYPE = 'SAVINGS' AND BALANCE >= 10000;

SELECT TRANSACTION_ID, AMOUNT
FROM TRANSACTIONS
WHERE TRANSACTION_TYPE = 'DEPOSIT' AND AMOUNT >= 1000;

SELECT LOAN_ID, AMOUNT
FROM LOANS
WHERE AMOUNT >= 50000 AND STATUS = 'PENDING';