-- 승인된 대출(APPROVED)의 총 대출 금액과 해당 대출 건수를 출력하시오
SELECT SUM(AMOUNT) TOTAL_AMOUNT, COUNT(*) COUNT
FROM LOANS
WHERE STATUS = 'APPROVED';

-- 각 월별 총 거래 금액을 계산하고, 거래 금액이 10,000 이상인 달만 출력하시오
--SELECT * FROM TRANSACTIONS;

SELECT MONTH, TOTAL_AMOUNT
FROM (SELECT EXTRACT(month FROM TRANSACTION_DATE) MONTH, SUM(AMOUNT) TOTAL_AMOUNT
        FROM TRANSACTIONS
        GROUP BY EXTRACT(month FROM TRANSACTION_DATE)
        ORDER BY MONTH)
WHERE TOTAL_AMOUNT >= 10000;
        

SELECT MONTH, TOTAL_AMOUNT
FROM (SELECT TO_CHAR(TRANSACTION_DATE, 'YYYY-MM') MONTH, SUM(AMOUNT) TOTAL_AMOUNT
        FROM TRANSACTIONS
        GROUP BY TO_CHAR(TRANSACTION_DATE, 'YYYY-MM')
        ORDER BY MONTH);
WHERE TOTAL_AMOUNT >= 10000;

-- 각 지점에서 승인된 대출(APPROVED)의 평균 대출 금액과 총 대출 금액을 계산하시오
--SELECT DISTINCT BRANCH_ID FROM LOANS ORDER BY BRANCH_ID; 

SELECT BRANCH_ID, AVG(AMOUNT) AVG_AMOUNT, SUM(AMOUNT) TOTAL_AMOUNT
FROM LOANS
GROUP BY BRANCH_ID
ORDER BY BRANCH_ID;
