-- 거래 테이블에서 계좌별 누적 거래 금액 계산
SELECT ACCOUNT_ID, AMOUNT,
        SUM(AMOUNT) OVER (PARTITION BY ACCOUNT_ID ORDER BY TRANSACTION_DATE) CUM_SUM,
        TRANSACTION_DATE
FROM TRANSACTIONS;

--
SELECT (SELECT CUSTOMER_ID FROM ACCOUNTS WHERE ACCOUNT_ID = T.ACCOUNT_ID) CUSTOMER_ID,
        ACCOUNT_ID, AMOUNT,
        SUM(AMOUNT) OVER (PARTITION BY ACCOUNT_ID ORDER BY TRANSACTION_DATE) CUM_SUM
FROM TRANSACTIONS T;

--
SELECT CUSTOMER_ID, ACCOUNT_ID, AMOUNT,
        SUM(AMOUNT) OVER (PARTITION BY ACCOUNT_ID ORDER BY TRANSACTION_DATE) CUM_SUM
FROM (SELECT CUSTOMER_ID, A.ACCOUNT_ID, NVL(AMOUNT, 0) AMOUNT
        FROM ACCOUNTS A
        LEFT OUTER JOIN TRANSACTIONS T
            ON A.ACCOUNT_ID = T.ACCOUNT_ID);


-- 각 계좌별 거래 금액의 최고 거래 금액 대비 비율 (AMOUNT/MAX AMOUNT)
SELECT ACCOUNT_ID, AMOUNT, AMOUNT/MAX(AMOUNT) OVER (PARTITION BY ACCOUNT_ID) AMOUNT_OVER_MAX
FROM TRANSACTIONS;


-- 대출 테이블에서 지점별 누적 대출 금액
SELECT DISTINCT BRANCH_ID, SUM(AMOUNT) OVER (PARTITION BY BRANCH_ID)
FROM LOANS;


-- 계좌 테이블에서 고객별 평균 잔액 (반올림하여 소수점 둘째 자리까지)
SELECT DISTINCT CUSTOMER_ID, ROUND(AVG(BALANCE) OVER (PARTITION BY CUSTOMER_ID), 2) AVG_BALANCE
FROM ACCOUNTS;

