-- 실습과제 2
SELECT NAME, PHONE
FROM CUSTOMERS
WHERE ADDRESS = 'Address 100';

SELECT ACCOUNT_ID, BALANCE 
FROM ACCOUNTS
WHERE BALANCE >= 50000;

SELECT TRANSACTION_ID, AMOUNT 
FROM TRANSACTIONS
WHERE AMOUNT < 0;

SELECT AMOUNT, CUSTOMER_ID
FROM LOANS
WHERE STATUS = 'APPROVED';
