CREATE TABLE USERS (
    UserID NUMBER PRIMARY KEY,
    Name VARCHAR2(50) NOT NULL,
    Email VARCHAR2(100) NOT NULL UNIQUE,
    Phone NUMBER UNIQUE,
    Address VARCHAR2(225),
    RegistrationDate DATE DEFAULT SYSDATE
);

CREATE TABLE ACCOUNT (
    AccountID NUMBER PRIMARY KEY,
    UserID NUMBER NOT NULL,
    Balance NUMBER DEFAULT 0,
    CreatedDate DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ACCOUNT_USERS FOREIGN KEY (UserID) REFERENCES USERS (UserID)
);

CREATE TABLE STOCK (
    StockID NUMBER PRIMARY KEY,
    CompanyName VARCHAR2(255) NOT NULL,
    Sector VARCHAR2(20),
    Market VARCHAR2(20) NOT NULL
);

CREATE TABLE "ORDER" (
    OrderID NUMBER PRIMARY KEY,
    AccountID NUMBER NOT NULL,
    StockID NUMBER NOT NULL,
    OrderType VARCHAR2(5) NOT NULL,
    Quantity NUMBER DEFAULT 0,
    Price NUMBER DEFAULT 0,
    OrderStatus VARCHAR2(10),
    OrderDate DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ORDER_ACCOUNT FOREIGN KEY (AccountID) REFERENCES ACCOUNT (AccountID),
    CONSTRAINT FK_ORDER_STOCK FOREIGN KEY (StockID) REFERENCES STOCK (StockID)
);

CREATE TABLE HOLDING (
    HoldingID NUMBER PRIMARY KEY,
    AccountID NUMBER NOT NULL,
    StockID NUMBER NOT NULL,
    Quantity NUMBER DEFAULT 0,
    AveragePrice NUMBER DEFAULT 0,
    LastUpdated DATE DEFAULT SYSDATE,
    CONSTRAINT FK_HOLDING_ACCOUNT FOREIGN KEY (AccountID) REFERENCES ACCOUNT (AccountID),
    CONSTRAINT FK_HOLDING_STOCK FOREIGN KEY (StockID) REFERENCES STOCK (StockID)
);


