SELECT * FROM CUSTOMERS;
SELECT * FROM ACCOUNT;
SELECT * FROM ACCOUNTS;
SELECT * FROM TRANSACTIONS;
SELECT * FROM LOANS;


-- 실습과제 1
SELECT NAME, EMAIL FROM CUSTOMERS;

SELECT ACCOUNT_ID, BALANCE FROM ACCOUNTS;

SELECT AMOUNT, TRANSACTION_TYPE FROM TRANSACTIONS;
