SELECT * FROM EMPLOYEES;
SELECT NAME, SALARY FROM EMPLOYEES;

SELECT * FROM DEPARTMENTS;

SELECT * FROM EMPLOYEES
WHERE department_id = 2;

-- COLUMN ALIAS
SELECT NAME AS EMPLOYEE_NAME,
    SALARY AS MONTHLY_SALARY
FROM EMPLOYEES;

SELECT SALARY*12 AS ANNUAL_SALARY
FROM EMPLOYEES;

-- TABLE ALIAS
SELECT E.NAME, E.SALARY
FROM EMPLOYEES E;

SELECT E.NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


SELECT E.NAME AS EMPLOYEE_NAME, D.DEPARTMENT_NAME AS DEPT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT E.NAME AS EMPLOYEE_NAME, D.DEPARTMENT_NAME AS DEPT_NAME
FROM EMPLOYEES E, DEPARTMENTS D;

SELECT E.NAME AS "이름", E.SALARY AS "급여"
FROM EMPLOYEES E;


SELECT NAME FROM EMPLOYEES WHERE SALARY > 5000;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 10;


SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID = 10 AND SALARY > 5000;

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID = 10 OR SALARY > 5000;

SELECT * FROM EMPLOYEES WHERE NOT SALARY > 5000;
SELECT * FROM EMPLOYEES WHERE SALARY <= 5000;

SELECT * FROM EMPLOYEES WHERE NAME LIKE '%1%';

SELECT * FROM FILES WHERE FILE_NAME LIKE 'DATA\_2024%' ESCAPE '\';

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (1, 2, 5);

SELECT * 
FROM EMPLOYEES
WHERE (MANAGER_ID, DEPARTMENT_ID) IN ((3, 5));


SELECT * FROM EMPLOYEES WHERE MANAGER_ID IS NULL;
SELECT * FROM EMPLOYEES WHERE MANAGER_ID IS NOT NULL;