-- 1.
-- 실행계획 확인 코드 - 통계치를 모든 레벨로 끌어올리는
ALTER SESSION SET STATISTICS_LEVEL=ALL;

SELECT * FROM EMPLOYEES WHERE ROWNUM <= 100;
SELECT * FROM table(dbms_xplan.display_cursor(NULL, NULL, 'ALLSTATS LAST'));

-- EMP_NO가 101이나 103으로 시작하는 직원 조회
SELECT * FROM EMPLOYEES
WHERE EMP_NO LIKE '101%'
    OR EMP_NO LIKE '103%';
    
SELECT * FROM table(dbms_xplan.display_cursor(NULL, NULL, 'ALLSTATS LAST'));

-- 튜닝
SELECT * FROM EMPLOYEES WHERE (EMP_NO BETWEEN 10100 AND 10199) OR (EMP_NO BETWEEN 10300 AND 10399);

SELECT * FROM EMPLOYEES WHERE (EMP_NO >= 10100 AND EMP_NO < 10199) OR (EMP_NO >= 10300 AND EMP_NO < 10399);


SELECT * FROM EMPLOYEES WHERE EMP_NO BETWEEN 10100 AND 10199
UNION ALL
SELECT * FROM EMPLOYEES WHERE EMP_NO BETWEEN 10300 AND 10399;

SELECT * FROM table(dbms_xplan.display_cursor(NULL, NULL, 'ALLSTATS LAST'));

-----
--2.
ALTER SESSION SET STATISTICS_LEVEL=ALL;

SELECT NVL(gender, 'NON') AS gender, COUNT(*)
FROM employees
GROUP BY NVL(gender, 'NON');

SELECT * FROM table(dbms_xplan.display_cursor(NULL, NULL, 'ALLSTATS LAST'));

--
SELECT gender, COUNT(*)
FROM employees
GROUP BY gender;


SELECT /*+ FULL(employees) */
DISTINCT gender AS gender, COUNT(*) OVER (PARTITION BY GENDER) FROM employees;


SELECT 
DISTINCT gender AS gender, COUNT(*) OVER (PARTITION BY GENDER) FROM employees;

SELECT /*+index(employees IDX_GENDER) */ gender, COUNT(*)
FROM employees
GROUP BY gender;


SELECT * FROM table(dbms_xplan.display_cursor(NULL, NULL, 'ALLSTATS LAST'));


----------
-- 3. 

ALTER SESSION SET STATISTICS_LEVEL=ALL;

SELECT *
FROM employees
WHERE GENDER||' '||LAST_NAME='M Radwan';




SELECT * FROM table(dbms_xplan.display_cursor(NULL, NULL, 'ALLSTATS LAST'));

--

SELECT *
FROM employees
WHERE GENDER='M' AND LAST_NAME= 'Radwan';

SELECT * FROM employees WHERE GENDER='M'
INTERSECT
SELECT * FROM employees WHERE LAST_NAME= 'Radwan';

SELECT * FROM table(dbms_xplan.display_cursor(NULL, NULL, 'ALLSTATS LAST'));


--------------
-- 4.
ALTER SESSION SET STATISTICS_LEVEL=ALL;

SELECT FIRST_NAME, LAST_NAME, EMP_NO
FROM EMPLOYEES
WHERE SUBSTR(EMP_NO, 1, 4) = 1030;

SELECT * FROM table(dbms_xplan.display_cursor(NULL, NULL, 'ALLSTATS LAST'));




SELECT FIRST_NAME, LAST_NAME, EMP_NO
FROM EMPLOYEES
WHERE EMP_NO BETWEEN 10300 AND 10309;

SELECT * FROM table(dbms_xplan.display_cursor(NULL, NULL, 'ALLSTATS LAST'));


---------
-- 5.
ALTER SESSION SET STATISTICS_LEVEL=ALL;

SELECT DISTINCT E.EMP_NO, E.FIRST_NAME, E.LAST_NAME, D.DEPT_NO
FROM EMPLOYEES E, DEPT_MANAGER D
WHERE E.EMP_NO = D.EMP_NO;

SELECT * FROM table(dbms_xplan.display_cursor(NULL, NULL, 'ALLSTATS LAST'));


--
SELECT DISTINCT E.EMP_NO, E.FIRST_NAME, E.LAST_NAME, (SELECT DEPT_NO FROM DEPT_MANAGER
WHERE E.EMP_NO = EMP_NO AND DEPT_NO IS NOT NULL)
FROM EMPLOYEES E;

SELECT DISTINCT E.EMP_NO, E.FIRST_NAME, E.LAST_NAME, 
        (SELECT DEPT_NO FROM DEPT_MANAGER D WHERE E.EMP_NO = D.EMP_NO AND DEPT_NO IS NOT NULL) 
FROM EMPLOYEES E;

SELECT *
FROM EMPLOYEES E;

SELECT * FROM DEPT_MANAGER;

SELECT E.EMP_NO, E.FIRST_NAME, E.LAST_NAME, D.DEPT_NO
FROM DEPT_MANAGER D, EMPLOYEES E
WHERE D.EMP_NO = E.EMP_NO;

SELECT E.EMP_NO, E.FIRST_NAME, E.LAST_NAME, D.DEPT_NO
FROM EMPLOYEES E, DEPT_MANAGER D
WHERE D.EMP_NO = E.EMP_NO;

SELECT E.EMP_NO, E.FIRST_NAME, E.LAST_NAME, D.DEPT_NO
FROM DEPT_MANAGER D, EMPLOYEES E
WHERE E.EMP_NO = D.EMP_NO;


SELECT /*+ ORDERED */E.EMP_NO, E.FIRST_NAME, E.LAST_NAME, D.DEPT_NO 
FROM EMPLOYEES E, DEPT_MANAGER D 
WHERE E.EMP_NO = D.EMP_NO;

SELECT * FROM table(dbms_xplan.display_cursor(NULL, NULL, 'ALLSTATS LAST'));
------
-- 6.
ALTER SESSION SET STATISTICS_LEVEL=ALL;

SELECT COUNT(DISTINCT E.EMP_NO) AS CNT
FROM EMPLOYEES E, (SELECT EMP_NO FROM SALARIES WHERE SALARY>50000) S
WHERE E.EMP_NO = S.EMP_NO;

SELECT * FROM table(dbms_xplan.display_cursor(NULL, NULL, 'ALLSTATS LAST'));



SELECT COUNT( E.EMP_NO) AS CNT
FROM EMPLOYEES E
WHERE EXISTS(SELECT 1 FROM SALARIES S WHERE E.EMP_NO = S.EMP_NO AND SALARY>50000) ;



WHERE E.EMP_NO = S.EMP_NO;


SELECT COUNT(SELECT S.EMP_NO FROM SALARIES S WHERE S.SALARY>50000 AND E.EMP_NO = S.EMP_NO) AS CNT
FROM EMPLOYEES E
;

SELECT COUNT(SELECT E.EMP_NO FROM EMPLOYEES E WHERE AND E.EMP_NO = S.EMP_NO) AS CNT 
FROM SALARIES S WHERE S.SALARY>50000;
AND E.EMP_NO = S.EMP_NO;



SELECT COUNT(DISTINCT EMP_NO) FROM SALARIES WHERE SALARY>50000;

SELECT COUNT(*)
FROM (SELECT EMP_NO, FROM_DATE FROM SALARIES WHERE SALARY>50000 GROUP BY EMP_NO, FROM_DATE);

SELECT EMP_NO, FROM_DATE FROM SALARIES WHERE SALARY>50000 GROUP BY EMP_NO,FROM_DATE;

SELECT /*+INDEX(SALARIES SYS_C008368)*/ EMP_NO, FROM_DATE FROM SALARIES WHERE EMP_NO BETWEEN 10000 AND 10100;


SELECT * FROM table(dbms_xplan.display_cursor(NULL, NULL, 'ALLSTATS LAST'));







