-- 각 지점의 이름과 대출 신청 고객의 정보를 출력하시오 (대출 신청 없는 지점 포함)
SELECT B.NAME BRANCH_NAME, C.CUSTOMER_NAME, AMOUNT
FROM BRANCHES B
LEFT OUTER JOIN (SELECT C.NAME CUSTOMER_NAME, L.AMOUNT AMOUNT, L.BRANCH_ID BRANCH_ID
                    FROM CUSTOMERS C
                    INNER JOIN LOANS L
                        ON C.CUSTOMER_ID = L.CUSTOMER_ID) C
    ON C.BRANCH_ID = B.BRANCH_ID
ORDER BY B.BRANCH_ID;


-- 잔액이 50000 이상인 계좌를 가진 고객의 이름과 이메일을 출력하시오
SELECT C.NAME, C.EMAIL, A.BALANCE
FROM CUSTOMERS C
INNER JOIN ACCOUNTS A
    ON C.CUSTOMER_ID = A.CUSTOMER_ID
WHERE A.BALANCE >= 50000;


-- 대출 상태가 PENDING인 대출을 신청한 고객 이름과 대출 금액을 조회하시오
SELECT C.NAME, L.AMOUNT
FROM CUSTOMERS C
INNER JOIN LOANS L
    ON C.CUSTOMER_ID = L.CUSTOMER_ID
WHERE L.STATUS = 'PENDING';

